package components

type GenericListEntity struct {
	Text_14                   string                              `json:"Text_14,omitempty"`
	Companies                 []GenericListCompanyEntity          `json:"Companies,omitempty"`
	Text_7                    string                              `json:"Text_7,omitempty"`
	Text_8                    string                              `json:"Text_8,omitempty"`
	DateValue_15              string                              `json:"DateValue_15,omitempty"`
	Text_6                    string                              `json:"Text_6,omitempty"`
	DateValue_14              string                              `json:"DateValue_14,omitempty"`
	DateValue_11              string                              `json:"DateValue_11,omitempty"`
	Text_16                   string                              `json:"Text_16,omitempty"`
	Text_18                   string                              `json:"Text_18,omitempty"`
	Text_11                   string                              `json:"Text_11,omitempty"`
	DateValue_2               string                              `json:"DateValue_2,omitempty"`
	Number_5                  float64                             `json:"Number_5,omitempty"`
	Text_25                   string                              `json:"Text_25,omitempty"`
	DateValue_12              string                              `json:"DateValue_12,omitempty"`
	Number_11                 float64                             `json:"Number_11,omitempty"`
	DateValue_6               string                              `json:"DateValue_6,omitempty"`
	Text_10                   string                              `json:"Text_10,omitempty"`
	DateValue_8               string                              `json:"DateValue_8,omitempty"`
	ListContent               string                              `json:"ListContent,omitempty"`
	Text_2                    string                              `json:"Text_2,omitempty"`
	LastUpdated               string                              `json:"LastUpdated"`
	DateValue_13              string                              `json:"DateValue_13,omitempty"`
	Text_22                   string                              `json:"Text_22,omitempty"`
	Number_12                 float64                             `json:"Number_12,omitempty"`
	Text_5                    string                              `json:"Text_5,omitempty"`
	DateValue_1               string                              `json:"DateValue_1,omitempty"`
	Text_19                   string                              `json:"Text_19,omitempty"`
	Number_8                  float64                             `json:"Number_8,omitempty"`
	Number_2                  float64                             `json:"Number_2,omitempty"`
	DateValue_7               string                              `json:"DateValue_7,omitempty"`
	Number_6                  float64                             `json:"Number_6,omitempty"`
	Number_15                 float64                             `json:"Number_15,omitempty"`
	Text_13                   string                              `json:"Text_13,omitempty"`
	Number_4                  float64                             `json:"Number_4,omitempty"`
	Text_4                    string                              `json:"Text_4,omitempty"`
	Text_3                    string                              `json:"Text_3,omitempty"`
	Text_12                   string                              `json:"Text_12,omitempty"`
	Text_20                   string                              `json:"Text_20,omitempty"`
	DateValue_10              string                              `json:"DateValue_10,omitempty"`
	Text_23                   string                              `json:"Text_23,omitempty"`
	DateValue_5               string                              `json:"DateValue_5,omitempty"`
	DateValue_9               string                              `json:"DateValue_9,omitempty"`
	Number_1                  float64                             `json:"Number_1,omitempty"`
	Text_24                   string                              `json:"Text_24,omitempty"`
	Number_10                 float64                             `json:"Number_10,omitempty"`
	Number_7                  float64                             `json:"Number_7,omitempty"`
	Text_21                   string                              `json:"Text_21,omitempty"`
	Text_1                    string                              `json:"Text_1,omitempty"`
	DateValue_4               string                              `json:"DateValue_4,omitempty"`
	Number_13                 float64                             `json:"Number_13,omitempty"`
	Text_15                   string                              `json:"Text_15,omitempty"`
	DateValue_3               string                              `json:"DateValue_3,omitempty"`
	Text_9                    string                              `json:"Text_9,omitempty"`
	ExternalCode              string                              `json:"ExternalCode" validate:"min=1,max=36"`
	Text_17                   string                              `json:"Text_17,omitempty"`
	Number_9                  float64                             `json:"Number_9,omitempty"`
	Number_14                 float64                             `json:"Number_14,omitempty"`
	Number_3                  float64                             `json:"Number_3,omitempty"`
}
